services:
  dev:
    image: dotfiles-dev
    build:
      dockerfile: Dockerfile.dev
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    command: bash -c "sleep infinity"
    working_dir: /home/user
